# %!Tex TS-program = xelatex
# %!TEX encoding = UTF-8 Unicode

#+AUTHOR: Pedro G. Branquinho, Wei-Liang Qian ({\ch{钱卫良}})
#+DATE: 1 Agosto 2021 a 31 Janeiro 2021
#+TITLE: Simulação e modelagem de tráfego e congestionamento.
# #+LATEX_HEADER: \usepackage{abntex2cite}
#+LATEX_HEADER: \usepackage[T1]{fontenc}		% Selecao de codigos de fonte.
#+LATEX_HEADER: \usepackage[utf8]{inputenc}		% Codificacao do documento (conversão automática dos acentos)
#+LATEX_HEADER: \usepackage{graphicx}			% Inclusão de gráficos
#+LATEX_HEADER: \usepackage{microtype} 			% para melhorias de
#+LATEX_HEADER: \bibliographystyle{abnt-num}
#+LATEX_HEADER: \RequireXeTeX %Force XeTeX check
#+LATEX_HEADER: \usepackage{xltxtra}
#+LATEX_HEADER: \usepackage{fontspec} %Font package
#+LATEX_HEADER: \newfontfamily\ch[Mapping=tex-text]{Noto Serif CJK TC}
# HAN NOM A
#+LATEX_HEADER: \DeclareTextFontCommand{\unifont}{\ch}



bibliography:~/Citations/global-bib.bib
# Conversei no setor de estágio e o Pedro poderá sim fazer o estágio,
# mas precisamos de um Projeto inicial (simplificado) com a data de
# início e término, as atividades que serão realizadas,  e após o
# término do estágio, o Pedro precisará entregar o relatório nos modelos
# solicitados pelo Setor de Estágio, ok?

# Então, aguardarei o Projeto, e assim que o Prof. Eduardo aprovar, já
# peço ao Pedro os documentos, abrirei o processo e enviarei ao Setor de
# Estágio, tudo bem?

* Projeto inicial
  Existem modelos físicos, os quais modelam o tráfego de carros,
  utilizando-se das equações da Hidrodinâmica cite:kerner1993cluster e
  da Cinética de Gases cite:bando1995dynamical. Na simulação desses
  modelos, precisa-se resolver Equações Diferenciais Parciais
  (EDPs). Assim, aprofundamento em técnicas de simulação numérica
  será desenvolvido.

  Programas e literaturas a nível de pós-graduação
  serão empregados, como o estudo das aulas do program de doutorado em
  métodos númericos em EPD's, ministradas por André Nachbin e
  disponível no YouTube. Aulas da Boston University, ME 702 -
  Computational Fluid Dynamics, ministradas pela professora Lorena
  A. Barba, também disponível na plataforma YouTube. Bem como, serão
  estados livros textos, com ênfase em física computational e análise de
  estabilidade computacional cite:press1986numerical.

  O objetivo inicial é a reprodução do artigo sobre instabilidade com
  pequenas pertubações, baseado em equações de Navier-Stokes
  cite:kerner1993cluster. Em seguida, propõe-se explorar condições de
  simulações ainda não constadas na literatura.
  
* Atividades a serem realizadas

  1. Estudo, anotação, e reprodução do curso integral de simulação de
     EDPs do programa de doutorado no Impa.
  2. Reprodução dos doze passos para simulação das equações de
     Navier-Stokes, proposto no curso de Lorena A. Barba.
    
     #+begin_quote
     + Steps 1–4 are in one dimension:
       (i) linear convection with a step-function initial condition (IC)
       and appropriate boundary conditions (BC); with the same IC/BCs:

       (ii) nonlinear convection, and

       (iii) diffusion only; with a saw-tooth IC and periodic BCs

       (iv) Burgers' equation.

     + Steps 5–10 are in two dimensions:

       (v) linear convection with square function IC and appropriate BCs;
       (vi)  nonlinear convection, with the same IC/BCs
       (vii) diffusion only, with the same IC/BCs;
       (viii) Burgers' equation;
       (ix)  Laplace equation, with zero IC and both Neumann and Dirichlet BCs;
       (x) Poisson equation in 2D.

     + Steps 11–12 solve the Navier-Stokes equation in 2D:
       (xi) cavity flow;
       (xii) channel flow.
     #+end_quote
      
  3. Análise das condições de instabilidade numérica do modelo de Kerner.
  4. Produção de resultados em estado da arte.

