#+STARTUP: latexpreview
#+STARTUP: inlineimages

bibliography:article-notes.bib

* Equation of continuity
 \begin{equation}
   \begin{aligned}
     \dfrac{\partial{\rho}}{\partial{t}} + \dfrac{\partial{\left( \rho{}v \right)}}{\partial{x}}=0
   \end{aligned}
 \end{equation}

* Navier-Stokes one-dimensional
Cited cite:schlichting2016boundary abud cite:Kerner_1993 

\begin{equation}
\begin{aligned}
\label{eq:NS-n1}
\rho{}\left[\frac{\partial{v}}{\partial{t}} + v\frac{\partial{v}}{\partial{x}} \right] = \dfrac{\partial \left(\mu \frac{\partial{v}}{x} \right)}{\partial{x}} - \dfrac{\partial{p}}{\partial{x}} + X
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
\begin{cases}
\rho : \textrm{Car density}\\
p: \textrm{Local car pressure}
v{}: \textrm{Car instant velocity}\\
\mu{}: \textrm{Viscosity}\\
X: \textrm{Sum of all inner particle interaction forces}
\end{cases}
\end{aligned}
\end{equation}

* Mathematical meanings of $X$ and $p$
** Relaxation process meaning
- If the perception is that current velocity $v$ is too slow compared
  to what can be safely achieved, then X is positive.
  - If the perception is that current velocity $v$ is too fast and
  dangerous compared to the traffic condition, then X is negative.
- Oscillatory behavior can appear.
  
** Consider the time independent homogeneous condition
\begin{equation}
\begin{aligned}
\begin{cases}
\label{eq:considerations}
&\langle\frac{\partial{v}}{\partial{x}}\rangle=0 \quad \textrm{(Time independent)} \\
&\langle\dfrac{\partial \left(\mu \frac{\partial{v}}{\partial{x}} \right)}{\partial{x}}\rangle=0 \quad \textrm{(Time independent and Homogeneous)} \\
\\
\quad \because \langle\dfrac{\partial \left(\mu \frac{\partial{v}}{\partial{x}} \right)}{\partial{x}}\rangle &=
\langle\dfrac{\partial \mu}{\partial{x}} \left( \frac{\partial{v}}{\partial{x}}\right)}\rangle +
\langle \mu \left( \dfrac{\partial^2{v}}{\partial^2{x}}\right)}\rangle \\

&\left((\langle\dfrac{\partial \mu}{\partial{x}}\rangle = 0  \quad \textrm{Homogeneous}) \,\land\, (\langle\dfrac{\partial^2{v}}{\partial^2{x}} \rangle = 0 \quad \textrm{Time independent and Homogeneous})\right)\\
&=0\\
\\
&\langle\frac{\partial{p}}{\partial{x}}\rangle=0 \quad \textrm{(Time independent)}
\end{cases}
\end{aligned}
\end{equation}

** X and acceleration; considerations of instant velocity
According to  [[ref:eq:NS-n1][ref:eq:NS-n1]] and X definition, under [[ref:eq:considerations][ref:eq:considerations]], we will have:
\begin{equation}
\begin{aligned}
\label{eq:NS-n1}
&(\rho{}\left[\frac{\partial{v}}{\partial{t}} + v\frac{\partial{v}}{\partial{x}} \right] = \dfrac{\partial \left(\mu \frac{\partial{v}}{\partial{x}} \right)}{\partial{x}} - \dfrac{\partial{p}}{\partial{x}} + X) \,\land\, (X = \rho{}. \dfrac{ (V(\rho) - v)}{\tau})\\
&\implies \frac{\textrm{d}v}{\textrm{d}t}=\frac{V(\rho) - v}{\tau}

\end{aligned}
\end{equation}

** $p$ pressure
\begin{equation}
\begin{aligned}
p = \rho{} c_0^2
\end{aligned}
\end{equation}
in which
- $\rho$ is the density.
- $c_0^2$ is the velocity variance. 

* Substitution of $(X,\, p)$ in terms of $\rho{},\,v,\,c_0$

This will be the equation we will use to simulate
\begin{equation}
\begin{aligned}
\label{eq:NS-n1}
\left[\frac{\partial{v}}{\partial{t}} + v\frac{\partial{v}}{\partial{x}} \right] = \frac{1}{\rho{}}\dfrac{\partial \left(\mu \frac{\partial{v}}{\partial{x}} \right)}{\partial{x}} - \left(\frac{c_0^2}{\rho{}}\right)\dfrac{\partial{\rho}}{\partial{x}} + \frac{V(\rho) - v}{\tau}
\end{aligned}
\end{equation}

- An equation of $(t,x,v,\rho)$.

* Julia Simulation

