#+startup: latexpreview
#+startup: imagepreview

* DONE Done
Pertubation Methods:
- Multiple Scales Expansion.
- Anharmonic Oscillator example.
https://www.math.arizona.edu/~ntna2007/Perturbation_Methods.pdf

* NEXT Reading
Title: *PHY-892 The Many-Body problem, from
perturbation theory to dynamical-mean Öeld
theory (lecture notes)*.

Author: André-Marie Tremblay

https://pitp.phas.ubc.ca/confs/sherbrooke2018/archives/N-corps-2017.pdf

* TODO Todo
http://galileoandeinstein.phys.virginia.edu/7010/CM_22_Resonant_Nonlinear_Oscillations.html
https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry_Textbook_Maps/Supplemental_Modules_(Physical_and_Theoretical_Chemistry)

* Spring-mass

Following *[[https://www.uio.no/studier/emner/matnat/fys/FYS3120/v14/undervisningsmateriale/smalloscillations.pdf][FYS 3120: Classical Mechanics and Electrodynamics]]*, considering:
** The equation of motion
\begin{equation}
\begin{aligned}
\ddot{q} = f(q, \dot{q})
\end{aligned}
\end{equation}

*** Mass-spring
In our case, mass-pring:

\begin{equation}
\begin{aligned}
m.\ddot{q} &= -k.q\\
\Leftrightarrow \ddot{q} &= - \frac{k}{m}q \, \land \, f(q,\dot{q})= - \frac{k}{m}q
\end{aligned}
\end{equation}

** Deviation from Equilibrium 
Let the variation from equilibrium be: $\rho = q - q_0$.

\begin{equation}
\begin{aligned}
\ddot{\rho} = f(q_0 + \rho{}, \dot{\rho{}})
\end{aligned}
\end{equation}

e.g.,
\begin{equation}
\begin{aligned}
q = \rho + q_0 \implies \dot{q} = \dot{\rho} \,\land\,\ddot{q} = \ddot{\rho}
\end{aligned}
\end{equation}

*** Mass-spring
In our spring-mass case,

\begin{equation}
\begin{aligned}
\ddot{\rho} = - \frac{k}{m}(q_0 + \rho)
\end{aligned}
\end{equation}

** Power expansion - Expansion around $(q_0,0)$

\begin{equation}
\begin{aligned}
\ddot{\rho} = f(q_0, 0) + \rho \dfrac{\partial{f}}{\partial{\rho}}(q_0,0) + \dot{\rho} \dfrac{\partial{f}}{\partial{\dot{\rho}}}(q_0,0)
\end{aligned}
\end{equation}

$f(q_0,0)=0\, \because\, q_0$ is equilibrium point: [[*The equation of motion][The equation of motion]] would be zero in this point.

We also neglect second order or higher terms.

*** Mass-spring
In our case,

\begin{equation}
\begin{aligned}
\ddot{\rho} = \rho \dfrac{\partial{f}}{\partial{\rho}}(q_0,0) + \dot{\rho} \dfrac{\partial{f}}{\partial{\dot{\rho}}}(q_0,0)\\
\end{aligned}
\end{equation}

in which,

\begin{equation}
\begin{aligned}
\left(\dfrac{\partial{f}}{\partial{\rho}}(\rho,\dot{\rho})
=- \dfrac{k}{m}\right) \, \land \, \left(\dfrac{\partial{\dot{f}}}{\partial{\dot{\rho}}}(\rho,\dot{\rho})=0\right)
\end{aligned}
\end{equation}

Therefore, in our case, the pertubation equation is:

\begin{equation}
\begin{aligned}
\ddot{\rho} = - \dfrac{k}{m}\rho
\end{aligned}
\end{equation}

\begin{equation}
\begin{aligned}
 \implies \rho(t) = A \sin{\left(\sqrt{\frac{k}{m}}t\right)} + B cos{\left(\sqrt{\frac{k}{m}}t\right)}
\end{aligned}
\end{equation}
**** Particular solution 
Particular case if $t_0 = 0$,

\begin{equation}
\begin{aligned}
\rho_0 &= B
\implies \rho(t) = \rho_0 \cos{\left(\sqrt{\frac{k}{m}}t\right)}
\end{aligned}
\end{equation}

**** General initical condition

If $\rho(t_0)=\rho_0$,

\begin{equation}
\begin{aligned}
\rho_0 &= A \sin{\left(\sqrt{\frac{k}{m}}t\right)} + B cos{\left(\sqrt{\frac{k}{m}}t\right)} \\
\Leftrightarrow  \rho_0 &= \left(\dfrac{A \sin{\left(\sqrt{\frac{k}{m}}t_0\right)} + B cos{\left(\sqrt{\frac{k}{m}}t_0\right)}}{\sqrt{A^2 + B^2}}\right). \sqrt{A^2 + B^2}
\end{aligned}
\end{equation}

Let the right-triangle with sides oposite side A and adjacent side B, with thus hippotenuse, $\sqrt{A^2 + B^2}$. This triangle define a angle $\alpha = \arctan{(\dfrac{A}{B})}$. So, $\sin{(\alpha)}= \dfrac{A}{\sqrt{A^2 + B^2}}$ and $\cos{(\alpha)}= \dfrac{B}{\sqrt{A^2 + B^2}}$.

\begin{equation}
\begin{aligned}
\implies \rho_0 &= (\sqrt{A^2 + B^2})\left(\sin{(\alpha)} \sin{\left(\sqrt{\frac{k}{m}}t_0\right)} + \cos{(\alpha)} cos{\left(\sqrt{\frac{k}{m}}t_0\right)}\right)\\
\therefore \rho_0 &= (\sqrt{A^2 + B^2}) \cos{\left(\sqrt{\frac{k}{m}}t_0 - \alpha\right)}
\end{aligned}
\end{equation}
