#+begin_src julia :session main :result output
  using Plots
#+end_src

#+RESULTS:

* Flux-Conservative Initial Value Problems (ยง19.1 Numerical recipes in C)
** Equations at hand
In general,
\begin{equation}
\begin{aligned}
\dfrac{\partial{\mathbf{u}}}{\partial{t}}=- \dfrac{\partial{\mathbf{F(u)}}}{\partial{x}}
\end{aligned}
\end{equation}

*** Advective equation
In particular,
\begin{equation}
\begin{aligned}
\dfrac{\partial{u}}{\partial{t}}=-v \dfrac{\partial{u}}{\partial{x}}
\end{aligned}
\end{equation}

with the known solution $u(x,y)=f(x-vt)$

** Descritize
\begin{equation}
\begin{aligned}
x_j = x_0 + j\Delta{}x, \quad j = 0, 1, \ldots, J\\
t_n = t_0 + n\Delta{}t, \quad n = 0, 1, \ldots, N
\end{aligned}
\end{equation}

- Let $u^n_j \equiv u(t_n,x_j)$.

** Foward Euler (Explicit)
*** Method definition
- First Order in time
    \begin{equation}
    \begin{aligned}
    \dfrac{\partial{u}}{\partial{t}}\biggr\rvert_{j,n} = \dfrac{u^{n+1}_j - u^n_j}{\Delta{t}} + O(\Delta{t})
    \end{aligned}
    \end{equation}
- Second Order in space
    \begin{equation}
    \begin{aligned}
    \dfrac{\partial{u}}{\partial{x}}\biggr\rvert_{j,n} = \dfrac{u^{n}_{j+1} - u^n_{j-1}}{2\Delta{x}} + O(\Delta{x^2})
    \end{aligned}
    \end{equation}
<<<<<<< HEAD
- Foward Time Centered Space (FTCS): *Generally*, unstable for hyperbolic probelms
=======
- Forward Time Centered Space (FTCS): *Generally*, unstable for hyperbolic probelms
>>>>>>> c079ef6 (Update state of reaserch)
*** Consequence
\begin{equation}
\begin{aligned}
\dfrac{u^{n+1}_j - u^n_j}{\Delta{t}} = -v \left( \dfrac{u^{n}_{j+1} - u^n_{j-1}}{2\Delta{x}} \right) 
\end{aligned}
\end{equation}
    
** von Neumman Stability Analysis
Local analysis,
*** Eigenmodes
\begin{equation}
\begin{aligned}
u^n_j = \xi{}^n e^{ikj \Delta{}x}
\end{aligned}
\end{equation}

As $\xi$ is powered to the $n$ power, it will converge only if
$|\xi{}|<1$.

- $\xi{}(k) \in \mathbb{C}$ is the /Amplification factor/.
- $k$ is a real spatial wave number.

* Discretizing PDE
** The equations
*** Motion
\begin{equation}
\begin{aligned}
\label{eq:NS-n1}
\left[\frac{\partial{v}}{\partial{t}} + v\frac{\partial{v}}{\partial{x}} \right] = \frac{1}{\rho{}}\dfrac{\partial \left(\mu \frac{\partial{v}}{\partial{x}} \right)}{\partial{x}} - \left(\frac{c_0^2}{\rho{}}\right)\dfrac{\partial{\rho}}{\partial{x}} + \frac{V(\rho) - v}{\tau}
\end{aligned}
\end{equation}

- An equation of $(t,x,v,\rho)$.
  
*** Conservation
 \begin{equation}
   \begin{aligned}
     \dfrac{\partial{\rho}}{\partial{t}} + \dfrac{\partial{\left( \rho{}v \right)}}{\partial{x}}=0
   \end{aligned}
 \end{equation}
 
*** Quantity of cars in the circuit
\begin{equation}
\begin{aligned}
N = \int_0^L{\rho{(x,t)} \textrm{d}x}=\rho_hL
\end{aligned}
\end{equation}
- $\rho_h$:= car density in homogeneous flow (equally dense in every
  point situation).
- $L$:= the road perimeter.
  
** Boundary Conditions
(Closed circuit)
\begin{equation}
\begin{aligned}
v(0,t) = v(L,t), \quad \dfrac{\partial{v}}{\partial{x}}\biggr\rvert_{0} = \dfrac{\partial{v}}{\partial{x}}\biggr\rvert_{L}
\end{aligned}
\end{equation}

* Thoughts
FW, BW approximation and Central Difference (CD).
- one change $\delta{}x$ in $\Delta{}x$ will lead to a change
  $2\delta$ in CD, but only $\delta$ in FW and BW.
